import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { cancelCloudJob, createCloudJob, getCloudJob, listCloudJobEvents, listCloudJobs, type CloudJob, type CloudJobEvent } from '../api/client'
import { useAuth } from '../auth/useAuth'

export function CloudTasksPage() {
  const { user } = useAuth(); const [jobs, setJobs] = useState<CloudJob[]>([]); const [selected, setSelected] = useState<CloudJob | null>(null); const [events, setEvents] = useState<CloudJobEvent[]>([]); const [task, setTask] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const eventCursor = useRef(-1)
  const load = useCallback(async () => { if (!user) return; try { setJobs((await listCloudJobs(user)).items) } catch (value) { setError(value instanceof Error ? value.message : 'Cloud tasks are unavailable.') } finally { setLoading(false) } }, [user])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (!user || !selected || !['queued', 'dispatching', 'starting', 'running', 'waiting_for_approval', 'cancelling'].includes(selected.status)) return; const timer = window.setInterval(() => { void getCloudJob(user, selected.id).then(value => { setSelected(value); void listCloudJobEvents(user, value.id, eventCursor.current).then(result => { if (result.items.length) { eventCursor.current = result.items.at(-1)?.sequence ?? eventCursor.current; setEvents(previous => [...previous, ...result.items]) } }).catch(() => undefined); void load() }).catch(() => undefined) }, 5_000); return () => window.clearInterval(timer) }, [user, selected, load])
  if (!user) return <main className="login-page"><section className="auth-card"><Link to="/login?returnTo=%2Ftasks">Sign in to view tasks</Link></section></main>
  const start = async () => { if (!task.trim()) return; setError(''); try { const job = await createCloudJob(user, task.trim()); setTask(''); setSelected(job); setEvents([]); await load() } catch (value) { setError(value instanceof Error ? value.message : 'Cloud tasks are unavailable.') } }
  const select = async (job: CloudJob) => { setSelected(job); eventCursor.current = -1; try { const result = await listCloudJobEvents(user, job.id); eventCursor.current = result.items.at(-1)?.sequence ?? -1; setEvents(result.items) } catch { setEvents([]) } }
  const cancel = async () => { if (!selected) return; try { const job = await cancelCloudJob(user, selected.id); setSelected(job); await load() } catch (value) { setError(value instanceof Error ? value.message : 'Cancellation failed.') } }
  return <main className="login-page"><section className="auth-card" style={{ maxWidth: 860, width: 'calc(100% - 32px)' }}><header><Link to="/">← Back to Swico</Link><h1>Cloud tasks</h1><p>Cloud coding runs are controlled by Swico and remain unavailable until an isolated runner is verified.</p></header><div style={{ display: 'flex', gap: 8, margin: '18px 0' }}><input aria-label="Cloud task" value={task} onChange={event => setTask(event.target.value)} placeholder="Describe a task for an isolated runner" maxLength={8000} /><button type="button" onClick={() => void start()} disabled={!task.trim()}>Start task</button></div>{error && <p role="alert">{error}</p>}{loading ? <p>Loading tasks…</p> : jobs.length ? <div style={{ display: 'grid', gridTemplateColumns: 'minmax(220px, 0.8fr) minmax(280px, 1.2fr)', gap: 20 }}>{<div>{jobs.map(job => <button key={job.id} type="button" onClick={() => void select(job)} style={{ display: 'block', width: '100%', textAlign: 'left', marginBottom: 8 }}><strong>{job.status}</strong><br /><small>{job.task.slice(0, 120)}</small></button>)}</div>}{selected && <article><h2>{selected.status}</h2><p>{selected.task}</p><p>Created {new Date(selected.created_at).toLocaleString()}</p>{['queued', 'dispatching', 'starting', 'running', 'waiting_for_approval', 'cancelling'].includes(selected.status) && <button type="button" onClick={() => void cancel()}>Cancel task</button>}<h3>Timeline</h3>{events.length ? <ol>{events.map(event => <li key={event.sequence}>{event.event_type} · {new Date(event.created_at).toLocaleString()}</li>)}</ol> : <p>No events recorded.</p>}{selected.failure_code && <p role="alert">Task failed: {selected.failure_code}</p>}</article>}</div> : <p>No tasks yet. Starting a task requires the cloud pilot to be enabled for this account.</p>}</section></main>
}
