apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.harishajahan.jai.wakeword'
version = '0.1.0'

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

try {
  def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
  apply from: expoModulesCorePlugin
  applyKotlinExpoModulesCorePlugin()
  useCoreDependencies()
  useDefaultAndroidSdkVersions()
} catch (Throwable ignored) {
  android {
    compileSdkVersion safeExtGet('compileSdkVersion', 35)
    defaultConfig {
      minSdkVersion safeExtGet('minSdkVersion', 23)
      targetSdkVersion safeExtGet('targetSdkVersion', 35)
    }
  }
  dependencies {
    implementation project(':expo-modules-core')
  }
}

android {
  namespace 'com.harishajahan.jai.wakeword'
}
