import { lstat, readdir, readFile, realpath } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import type { RepositoryMetadata } from './repository.js'
export type SwicoPlugin = { name: string; version: string; description?: string; skills?: string[]; mcp?: string[]; hooks?: string[]; path: string }
const forbidden = new Set(['main', 'entry', 'scripts', 'dependencies', 'install'])
export function validatePlugin(value: unknown, path: string): SwicoPlugin { if (!value || typeof value !== 'object') throw new Error('Plugin manifest must be an object.'); const item = value as Record<string, unknown>; for (const key of forbidden) if (key in item) throw new Error(`Plugin manifest cannot contain executable field '${key}'.`); if (typeof item.name !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(item.name) || typeof item.version !== 'string') throw new Error('Plugin manifest requires a safe name and version.'); const arrays = (key: string) => item[key] === undefined ? [] : Array.isArray(item[key]) && item[key].every(value => typeof value === 'string' && value.length < 256) ? item[key] as string[] : (() => { throw new Error(`Plugin ${key} must be a bounded string array.`) })(); return { name: item.name, version: item.version, description: typeof item.description === 'string' ? item.description.slice(0, 512) : undefined, skills: arrays('skills'), mcp: arrays('mcp'), hooks: arrays('hooks'), path }
}
export async function inspectPlugin(path: string): Promise<SwicoPlugin> { const real = await realpath(resolve(path)), manifest = real.endsWith('swico-plugin.json') ? real : join(real, 'swico-plugin.json'); const info = await lstat(manifest); if (!info.isFile() || info.isSymbolicLink()) throw new Error('Plugin manifest must be a regular local file.'); const text = await readFile(manifest, 'utf8'); if (Buffer.byteLength(text) > 32 * 1024) throw new Error('Plugin manifest is too large.'); return validatePlugin(JSON.parse(text), manifest) }
export async function listPlugins(metadata?: RepositoryMetadata, cwd = process.cwd()): Promise<SwicoPlugin[]> { const paths = [join(cwd, '.swico', 'plugins'), ...(metadata ? [join(metadata.root, '.swico', 'plugins')] : [])]; const result: SwicoPlugin[] = []; for (const directory of paths) { try { for (const entry of await readdir(directory, { withFileTypes: true })) if (entry.isDirectory() && !entry.isSymbolicLink()) try { result.push(await inspectPlugin(join(directory, entry.name))) } catch { /* inspect command reports malformed manifests */ } } catch { /* optional directory */ } } return result.slice(0, 32) }
