import { lstat, readFile, readdir, realpath } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join, relative, resolve } from 'node:path'
import type { RepositoryMetadata } from './repository.js'

export type Skill = { name: string; description: string; path: string; source: 'user' | 'project'; instructions?: string }
const MAX_SKILLS = 64, MAX_METADATA = 32 * 1024, MAX_INSTRUCTIONS = 32 * 1024
function userSkillsPath(env: NodeJS.ProcessEnv = process.env): string { return join(env.XDG_CONFIG_HOME ?? (process.platform === 'win32' ? env.APPDATA ?? join(homedir(), 'AppData', 'Roaming') : join(homedir(), '.config')), 'swico', 'skills') }
function projectSkillsPath(root: string): string { return join(root, '.swico', 'skills') }
function inside(root: string, candidate: string): boolean { const value = relative(root, candidate).replaceAll('\\', '/'); return value === '' || (!value.startsWith('../') && value !== '..' && !value.includes('/../')) }
function frontmatter(text: string): { name?: string; description?: string; body: string } { const match = /^---\s*\n([\s\S]*?)\n---\s*\n?/.exec(text); const fields: Record<string, string> = {}; if (match) for (const line of match[1].split(/\r?\n/)) { const entry = /^([A-Za-z_-]+):\s*(.+)$/.exec(line); if (entry) fields[entry[1]] = entry[2].replace(/^['"]|['"]$/g, '').slice(0, 256) } const body = (match ? text.slice(match[0].length) : text); const heading = /^#\s+(.+)$/m.exec(body); const paragraph = body.split(/\r?\n\s*\r?\n/).find(value => value.trim()); return { name: fields.name ?? heading?.[1]?.trim(), description: fields.description ?? paragraph?.replace(/\s+/g, ' ').trim().slice(0, 512), body }
}
async function scan(directory: string, source: 'user' | 'project', root: string): Promise<Skill[]> { const result: Skill[] = []; let entries: Awaited<ReturnType<typeof readdir>>; try { entries = await readdir(directory, { withFileTypes: true }) } catch { return result } for (const entry of entries.slice(0, MAX_SKILLS)) { if (!entry.isDirectory() || entry.isSymbolicLink()) continue; const file = join(directory, entry.name, 'SKILL.md'); try { const info = await lstat(file); if (!info.isFile() || info.isSymbolicLink()) continue; const real = await realpath(file); if (!inside(root, real) && source === 'project') continue; const parsed = frontmatter((await readFile(real, 'utf8')).slice(0, MAX_INSTRUCTIONS)); if (!parsed.name || !parsed.description) continue; result.push({ name: parsed.name.replace(/[^A-Za-z0-9_-]/g, '-').slice(0, 64), description: parsed.description, path: real, source }) } catch { /* malformed skills are ignored */ } } return result }
export async function listSkills(metadata?: RepositoryMetadata, cwd = process.cwd(), env: NodeJS.ProcessEnv = process.env): Promise<Skill[]> { const user = await scan(userSkillsPath(env), 'user', resolve(cwd)); const project = metadata ? await scan(projectSkillsPath(metadata.root), 'project', metadata.root) : []; const byName = new Map<string, Skill>(); for (const item of [...user, ...project]) byName.set(item.name, item); return [...byName.values()].slice(0, MAX_SKILLS) }
export async function showSkill(name: string, metadata?: RepositoryMetadata, cwd = process.cwd(), env: NodeJS.ProcessEnv = process.env): Promise<Skill> { const item = (await listSkills(metadata, cwd, env)).find(value => value.name === name); if (!item) throw new Error(`Skill '${name}' was not found.`); return { ...item, instructions: (await readFile(item.path, 'utf8')).slice(0, MAX_INSTRUCTIONS) } }
export function selectSkill(task: string, skills: Skill[], auto = true): Skill | null { const explicit = /^\$([A-Za-z0-9_-]+)/.exec(task)?.[1]; if (explicit) return skills.find(item => item.name === explicit) ?? null; if (!auto) return null; const words = new Set(task.toLowerCase().split(/[^a-z0-9]+/).filter(value => value.length > 2)); return skills.map(item => ({ item, score: item.description.toLowerCase().split(/[^a-z0-9]+/).filter(word => words.has(word)).length })).sort((a, b) => b.score - a.score)[0]?.score ? skills.map(item => ({ item, score: item.description.toLowerCase().split(/[^a-z0-9]+/).filter(word => words.has(word)).length })).sort((a, b) => b.score - a.score)[0].item : null }
